Update files and instructions for running in production environment
TwilioDevEd/video-access-token-server-python pull request #89
Opened 2021-10-28 23:17 UTC by Larox

This PR includes:

- Add `DEBUG` variable to `.env.example` file
- Update `Readme.md` instructions for `DEBUG` variable

2021-11-04 18:57 UTC, Larox commented on .env.example
> +DEBUG=True
That's right updating it.

2021-11-04 22:00 UTC, jefflinwood requested changes
Hi, This needs one minor wording change and then it can be merged.

2021-11-08 18:54 UTC, Larox commented on README.md
> +by default in `production` environment. Feel free to update `DEBUG` to False if needed.
Updated!

2021-11-08 19:56 UTC, jefflinwood commented
Thanks!

2021-11-08 19:56 UTC, merged